### ISSUE TITLE
Is it a diffirentiable renderer?

### ISSUE THREAD

**Issue by gsygsy96** [tvytlx/render-py#9]
Fantastic project! My concern is whether it is diffirentiable?

**Comment by tvytlx** [comment]
Actually, I wrote this project for education purpose, it's not a practical renderer. (the rendered results output to an image for simplification)

From the inside, It's written in almost pure Python, no OpenGL/DirectX, the code is mainly used to show the principle and theory of Computer Graphics.

So, Is it a differentiable renderer? Yes, it's for better teaching! (I hope)

**Comment by gsygsy96** [comment]
Thanks! Your contribution is really impressive and grateful. 
One more thing, a differentiable renderer is enough to be write as a paper. Maybe you can consider it :P
